# Generated by Django 5.2.12 on 2026-03-17 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub Issues'), ('algora', 'Algora'), ('opire', 'Opire'), ('gitcoin', 'Gitcoin'), ('issuehunt', 'IssueHunt'), ('hackerone', 'HackerOne'), ('bugcrowd', 'Bugcrowd'), ('immunefi', 'Immunefi'), ('code4rena', 'Code4rena'), ('other', 'Other')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bounties_found', models.IntegerField(default=0)),
                ('bounties_new', models.IntegerField(default=0)),
                ('bounties_updated', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Platform-specific ID', max_length=255)),
                ('platform', models.CharField(choices=[('github', 'GitHub Issues'), ('algora', 'Algora'), ('opire', 'Opire'), ('gitcoin', 'Gitcoin'), ('issuehunt', 'IssueHunt'), ('hackerone', 'HackerOne'), ('bugcrowd', 'Bugcrowd'), ('immunefi', 'Immunefi'), ('code4rena', 'Code4rena'), ('other', 'Other')], max_length=20)),
                ('source_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('repo_owner', models.CharField(max_length=255)),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_url', models.URLField(max_length=500)),
                ('issue_number', models.IntegerField(blank=True, null=True)),
                ('bounty_amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_currency', models.CharField(blank=True, default='', max_length=10)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('languages', models.JSONField(blank=True, default=list, help_text='All languages in repo')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('competitors_count', models.IntegerField(default=0, help_text='Number of people working on this')),
                ('existing_prs', models.IntegerField(default=0, help_text='PRs already submitted')),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('evaluated', 'Evaluated'), ('targeted', 'Targeted'), ('in_progress', 'In Progress'), ('solved', 'Solved'), ('submitted', 'PR Submitted'), ('merged', 'PR Merged'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('abandoned', 'Abandoned'), ('expired', 'Expired')], default='discovered', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'bounties',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['status'], name='bounty_mode_status_65e13a_idx'), models.Index(fields=['platform', 'status'], name='bounty_mode_platfor_cc108c_idx'), models.Index(fields=['bounty_amount_usd'], name='bounty_mode_bounty__26130d_idx'), models.Index(fields=['-discovered_at'], name='bounty_mode_discove_dd97dc_idx')],
                'unique_together': {('platform', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_score', models.FloatField(help_text='Overall ROI score 0-100')),
                ('difficulty_score', models.FloatField(help_text='Difficulty 0-100 (lower = easier)')),
                ('tech_match_score', models.FloatField(help_text='How well our stack matches 0-100')),
                ('competition_score', models.FloatField(help_text='Competition factor 0-100 (lower = less competition)')),
                ('repo_quality_score', models.FloatField(help_text='Repo quality 0-100')),
                ('estimated_hours', models.FloatField(help_text='Estimated hours to complete')),
                ('estimated_difficulty', models.CharField(choices=[('trivial', 'Trivial'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=10)),
                ('effective_hourly_rate', models.DecimalField(decimal_places=2, help_text='$/hr if we win', max_digits=10)),
                ('analysis_summary', models.TextField(help_text="AI's analysis of the issue")),
                ('approach_suggestion', models.TextField(blank=True, default='', help_text='Suggested approach')),
                ('risks', models.JSONField(default=list, help_text='Identified risks')),
                ('required_skills', models.JSONField(default=list)),
                ('has_clear_requirements', models.BooleanField(default=True)),
                ('has_tests', models.BooleanField(default=False, help_text='Repo has test suite')),
                ('has_ci', models.BooleanField(default=False, help_text='Repo has CI/CD')),
                ('has_contribution_guide', models.BooleanField(default=False)),
                ('auto_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('bounty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='bounty_models.bounty')),
            ],
            options={
                'ordering': ['-roi_score'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fork_url', models.URLField(blank=True, default='', max_length=500)),
                ('branch_name', models.CharField(blank=True, default='', max_length=255)),
                ('local_path', models.CharField(blank=True, default='', max_length=500)),
                ('implementation_plan', models.TextField(blank=True, default='')),
                ('files_changed', models.JSONField(default=list)),
                ('diff_summary', models.TextField(blank=True, default='')),
                ('tests_added', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('exploring', 'Exploring Codebase'), ('planning', 'Planning Implementation'), ('coding', 'Coding Solution'), ('testing', 'Running Tests'), ('reviewing', 'Internal Review'), ('iterating', 'Iterating on Feedback'), ('ready', 'Ready for Submission'), ('failed', 'Failed')], default='exploring', max_length=20)),
                ('iteration_count', models.IntegerField(default=0)),
                ('max_iterations', models.IntegerField(default=3)),
                ('all_tests_pass', models.BooleanField(default=False)),
                ('lint_clean', models.BooleanField(default=False)),
                ('review_approved', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('agent_cost_usd', models.DecimalField(decimal_places=4, default=0, help_text='AI inference cost', max_digits=8)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='bounty_models.bounty')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_url', models.URLField(max_length=500)),
                ('pr_number', models.IntegerField()),
                ('pr_title', models.CharField(max_length=500)),
                ('pr_body', models.TextField()),
                ('pr_status', models.CharField(choices=[('submitted', 'Submitted'), ('review_requested', 'Review Requested'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('merged', 'Merged'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('review_comments', models.JSONField(default=list, help_text='Review comments received')),
                ('response_count', models.IntegerField(default=0, help_text="Times we've responded to reviews")),
                ('bounty_claimed', models.BooleanField(default=False)),
                ('bounty_claim_url', models.URLField(blank=True, default='', max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='bounty_models.bounty')),
                ('solution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='bounty_models.solution')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agent_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_earning_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('total_time_hours', models.FloatField(help_text='Total hours from discovery to merge')),
                ('effective_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bounty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='bounty_models.bounty')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='bounty_models.submission')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
    ]
