use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use std::path::PathBuf;
use std::process::Command;
use std::fs;

#[derive(Parser)]
#[command(
    name = "w3cos",
    about = "W3C OS — compile TypeScript to native binaries",
    version,
    long_about = "Compile W3C Modern Subset TypeScript/CSS into native Linux/macOS binaries.\n\
                   No browser. No interpreter. No V8. Pure native."
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Compile a .ts or .json app into a native binary.
    Build {
        /// Path to the TypeScript or JSON source file.
        input: PathBuf,
        /// Output binary path (default: ./app).
        #[arg(short, long, default_value = "./app")]
        output: PathBuf,
        /// Build in release mode (optimized, smaller binary).
        #[arg(long)]
        release: bool,
    },
    /// Compile and immediately run the application.
    Run {
        /// Path to the TypeScript or JSON source file.
        input: PathBuf,
    },
    /// Initialize a new W3C OS project with template files.
    Init {
        /// Project name (creates a directory with this name).
        project_name: PathBuf,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Build {
            input,
            output,
            release,
        } => {
            build(&input, &output, release)?;
        }
        Commands::Run { input } => {
            let tmp = std::env::temp_dir().join("w3cos-run");
            let bin = tmp.join("target").join("debug").join("w3cos-app");
            build(&input, &bin, false)?;
            println!("▶  Running...");
            let status = Command::new(&bin)
                .status()
                .context("Failed to run compiled binary")?;
            std::process::exit(status.code().unwrap_or(1));
        }
        Commands::Init { project_name } => {
            init(&project_name)?;
        }
    }

    Ok(())
}

fn build(input: &PathBuf, output: &PathBuf, release: bool) -> Result<()> {
    let source = std::fs::read_to_string(input)
        .with_context(|| format!("Could not read {}", input.display()))?;

    let build_dir = std::env::temp_dir().join("w3cos-build");
    if build_dir.exists() {
        std::fs::remove_dir_all(&build_dir)?;
    }

    println!("⚡ Transpiling {} → Rust...", input.display());
    w3cos_compiler::compile(&source, &build_dir)?;

    println!("🔨 Compiling native binary...");
    let mut cmd = Command::new("cargo");
    cmd.arg("build").current_dir(&build_dir);
    if release {
        cmd.arg("--release");
    }

    let status = cmd.status().context("cargo build failed")?;
    if !status.success() {
        anyhow::bail!("Compilation failed");
    }

    let profile = if release { "release" } else { "debug" };
    let built_bin = build_dir.join("target").join(profile).join("w3cos-app");

    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::copy(&built_bin, output)
        .with_context(|| format!("Could not copy binary to {}", output.display()))?;

    let size = std::fs::metadata(output)?.len();
    let size_str = if size > 1_000_000 {
        format!("{:.1} MB", size as f64 / 1_000_000.0)
    } else {
        format!("{:.0} KB", size as f64 / 1_000.0)
    };

    println!("✅ Output: {} ({})", output.display(), size_str);
    Ok(())
}

fn init(project_name: &PathBuf) -> Result<()> {
    println!("🚀 Initializing W3C OS project: {}", project_name.display());

    // Check if directory already exists
    if project_name.exists() {
        anyhow::bail!("Error: Directory '{}' already exists", project_name.display());
    }

    // Create project directory
    fs::create_dir_all(project_name)
        .with_context(|| format!("Could not create directory {}", project_name.display()))?;

    // Create app.ts template
    let app_ts_path = project_name.join("app.ts");
    let app_ts_content = r#"// W3C OS Application Template
// Generated by w3cos init

import { Application } from '@w3cos/core';

const app = new Application({
    title: 'My W3C App',
    width: 800,
    height: 600,
});

app.on('ready', () => {
    console.log('Hello, W3C OS!');
});

app.start();
"#;
    fs::write(&app_ts_path, app_ts_content)
        .with_context(|| format!("Could not create {}", app_ts_path.display()))?;
    println!("✅ Created: {}", app_ts_path.display());

    // Create README.md
    let readme_path = project_name.join("README.md");
    let readme_content = format!(r#"# {}

A W3C OS Application.

## Getting Started

### Prerequisites

- Rust (latest stable)
- w3cos CLI

### Installation

```bash
# Install dependencies
cargo build

# Run the application
w3cos run app.ts

# Or build a native binary
w3cos build app.ts -o myapp

# Run the binary
./myapp
```

## Project Structure

```
{}
├── app.ts          # Main application entry point
├── README.md       # This file
└── Cargo.toml      # Rust dependencies (if needed)
```

## Development

### Hot Reload

```bash
w3cos run app.ts
```

### Build Release

```bash
w3cos build app.ts -o myapp --release
```

## License

Apache-2.0
"#, project_name.display(), project_name.display());
    fs::write(&readme_path, readme_content)
        .with_context(|| format!("Could not create {}", readme_path.display()))?;
    println!("✅ Created: {}", readme_path.display());

    println!("\n✨ Project initialized successfully!");
    println!("📁 Next steps:");
    println!("   cd {}", project_name.display());
    println!("   w3cos run app.ts");

    Ok(())
}
