#!/usr/bin/env python3
"""
文档格式转换器 - 支持多种输出格式

支持格式：
- Markdown → HTML
- HTML → PDF（可选）
"""

import logging
import re
from typing import Optional
from pathlib import Path

# 日志配置
logger = logging.getLogger(__name__)


class DocumentConverter:
    """文档格式转换器"""
    
    def __init__(self):
        self.logger = logging.getLogger(__name__)
    
    def markdown_to_html(self, markdown: str, title: str = "Documentation") -> str:
        """Markdown 转 HTML"""
        try:
            import markdown
            
            # 配置扩展
            extensions = [
                'extra',           # 额外功能（表格、代码块等）
                'codehilite',      # 代码高亮
                'toc',             # 目录
                'tables',          # 表格
                'fenced_code',     # 围栏代码块
            ]
            
            html_content = markdown.markdown(
                markdown,
                extensions=extensions,
                output_format='html5'
            )
            
            # 包装成完整 HTML
            html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #24292e;
            max-width: 920px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
        }}
        
        h1, h2, h3, h4, h5, h6 {{
            margin-top: 24px;
            margin-bottom: 16px;
            font-weight: 600;
            line-height: 1.25;
        }}
        
        h1 {{
            font-size: 2em;
            border-bottom: 1px solid #eaecef;
            padding-bottom: .3em;
        }}
        
        h2 {{
            font-size: 1.5em;
            border-bottom: 1px solid #eaecef;
            padding-bottom: .3em;
        }}
        
        h3 {{ font-size: 1.25em; }}
        h4 {{ font-size: 1em; }}
        
        a {{
            color: #0366d6;
            text-decoration: none;
        }}
        
        a:hover {{
            text-decoration: underline;
        }}
        
        code {{
            padding: .2em .4em;
            margin: 0;
            font-size: 85%;
            background-color: rgba(27,31,35,.05);
            border-radius: 3px;
            font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace;
        }}
        
        pre {{
            padding: 16px;
            overflow: auto;
            font-size: 85%;
            line-height: 1.45;
            background-color: #f6f8fa;
            border-radius: 3px;
        }}
        
        pre code {{
            background-color: transparent;
            padding: 0;
        }}
        
        blockquote {{
            padding: 0 1em;
            color: #6a737d;
            border-left: .25em solid #dfe2e5;
            margin: 0 0 16px 0;
        }}
        
        table {{
            border-spacing: 0;
            border-collapse: collapse;
            margin-bottom: 16px;
            width: 100%;
        }}
        
        table th,
        table td {{
            padding: 6px 13px;
            border: 1px solid #dfe2e5;
        }}
        
        table th {{
            font-weight: 600;
            background-color: #f6f8fa;
        }}
        
        table tr:nth-child(2n) {{
            background-color: #f6f8fa;
        }}
        
        img {{
            max-width: 100%;
            box-sizing: content-box;
            background-color: #fff;
        }}
        
        .toc {{
            background-color: #f6f8fa;
            border: 1px solid #eaecef;
            padding: 16px;
            margin-bottom: 24px;
            border-radius: 3px;
        }}
        
        .toc ul {{
            list-style: none;
            padding-left: 0;
        }}
        
        .toc ul ul {{
            padding-left: 20px;
        }}
        
        .toc li {{
            margin: 4px 0;
        }}
        
        .codehilite {{
            background-color: #f6f8fa;
            border-radius: 3px;
        }}
    </style>
</head>
<body>
    <article class="markdown-body">
{html_content}
    </article>
    
    <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eaecef; color: #6a737d; font-size: 0.9em;">
        Generated by <a href="https://github.com/yourorg/auto-document-generator">Auto Document Generator</a>
    </footer>
</body>
</html>"""
            
            return html
            
        except ImportError:
            self.logger.warning("markdown package not available, using basic conversion")
            return self._basic_markdown_to_html(markdown, title)
        except Exception as e:
            self.logger.error(f"Markdown to HTML conversion failed: {e}")
            return self._basic_markdown_to_html(markdown, title)
    
    def _basic_markdown_to_html(self, markdown: str, title: str) -> str:
        """基础 Markdown 转 HTML（无依赖）"""
        # 转换标题
        markdown = re.sub(r'^### (.*?)$', r'<h3>\1</h3>', markdown, flags=re.MULTILINE)
        markdown = re.sub(r'^## (.*?)$', r'<h2>\1</h2>', markdown, flags=re.MULTILINE)
        markdown = re.sub(r'^# (.*?)$', r'<h1>\1</h1>', markdown, flags=re.MULTILINE)
        
        # 转换代码块
        markdown = re.sub(r'```(\w+)?\n(.*?)\n```', r'<pre><code class="\1">\2</code></pre>', markdown, flags=re.DOTALL)
        
        # 转换行内代码
        markdown = re.sub(r'`(.*?)`', r'<code>\1</code>', markdown)
        
        # 转换粗体
        markdown = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', markdown)
        
        # 转换斜体
        markdown = re.sub(r'\*(.*?)\*', r'<em>\1</em>', markdown)
        
        # 转换链接
        markdown = re.sub(r'\[(.*?)\]\((.*?)\)', r'<a href="\2">\1</a>', markdown)
        
        # 转换段落
        paragraphs = markdown.split('\n\n')
        html_paragraphs = []
        for p in paragraphs:
            if p.strip() and not p.strip().startswith('<'):
                html_paragraphs.append(f'<p>{p}</p>')
            else:
                html_paragraphs.append(p)
        
        html_content = '\n'.join(html_paragraphs)
        
        # 包装成完整 HTML
        html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            line-height: 1.6;
            max-width: 920px;
            margin: 0 auto;
            padding: 20px;
        }}
        pre {{
            background-color: #f6f8fa;
            padding: 16px;
            border-radius: 3px;
            overflow-x: auto;
        }}
        code {{
            font-family: SFMono-Regular, Consolas, monospace;
            background-color: rgba(27,31,35,.05);
            padding: .2em .4em;
            border-radius: 3px;
        }}
    </style>
</head>
<body>
{html_content}
</body>
</html>"""
        
        return html
    
    def html_to_pdf(self, html: str, output_path: str) -> bool:
        """HTML 转 PDF"""
        try:
            import weasyprint
            
            # 生成 PDF
            weasyprint.HTML(string=html).write_pdf(output_path)
            
            self.logger.info(f"PDF generated: {output_path}")
            return True
            
        except ImportError:
            self.logger.warning("weasyprint not available, PDF generation disabled")
            return False
        except Exception as e:
            self.logger.error(f"HTML to PDF conversion failed: {e}")
            return False
    
    def add_syntax_highlighting(self, html: str) -> str:
        """添加语法高亮（使用 Pygments）"""
        try:
            from pygments import highlight
            from pygments.lexers import get_lexer_by_name, guess_lexer
            from pygments.formatters import HtmlFormatter
            
            # 查找代码块
            pattern = r'<pre><code class="(\w+)">(.*?)</code></pre>'
            
            def replace_code(match):
                lang = match.group(1)
                code = match.group(2)
                
                try:
                    lexer = get_lexer_by_name(lang, stripall=True)
                except:
                    lexer = guess_lexer(code)
                
                formatter = HtmlFormatter()
                highlighted = highlight(code, lexer, formatter)
                
                return highlighted
            
            html = re.sub(pattern, replace_code, html, flags=re.DOTALL)
            
            # 添加样式
            css = HtmlFormatter().get_style_defs('.highlight')
            style_tag = f'<style>{css}</style>'
            
            if '</head>' in html:
                html = html.replace('</head>', f'{style_tag}</head>')
            
            return html
            
        except ImportError:
            self.logger.warning("pygments not available, syntax highlighting disabled")
            return html
        except Exception as e:
            self.logger.error(f"Syntax highlighting failed: {e}")
            return html
    
    def convert(self, content: str, from_format: str, to_format: str, **kwargs) -> str:
        """通用格式转换"""
        if from_format == 'markdown' and to_format == 'html':
            return self.markdown_to_html(content, **kwargs.get('title', 'Documentation'))
        elif from_format == 'html' and to_format == 'pdf':
            output_path = kwargs.get('output_path', 'output.pdf')
            success = self.html_to_pdf(content, output_path)
            return "PDF generated" if success else "PDF generation failed"
        else:
            self.logger.error(f"Unsupported conversion: {from_format} → {to_format}")
            return content
