#!/usr/bin/env python3
"""
文档更新检测器 - 监听文件变更并自动更新文档

支持策略：
- Git Hooks (pre-commit, post-commit)
- 文件监听 (watchdog)
- CI/CD 集成 (GitHub Actions)
"""

import logging
import time
import hashlib
from pathlib import Path
from typing import Optional, List, Dict, Set
from dataclasses import dataclass
from datetime import datetime

# 日志配置
logger = logging.getLogger(__name__)


@dataclass
class FileChange:
    """文件变更信息"""
    file_path: str
    change_type: str  # 'added', 'modified', 'deleted'
    old_hash: Optional[str] = None
    new_hash: Optional[str] = None
    timestamp: datetime = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()


class DocumentWatcher:
    """文档更新检测器"""
    
    def __init__(
        self,
        input_dir: str,
        output_dir: str = "docs/",
        format: str = "markdown",
        use_ai: bool = False,
        model: str = "llama3"
    ):
        self.input_dir = Path(input_dir)
        self.output_dir = Path(output_dir)
        self.format = format
        self.use_ai = use_ai
        self.model = model
        
        self.logger = logging.getLogger(__name__)
        
        # 文件哈希缓存
        self.file_hashes: Dict[str, str] = {}
        
        # 支持的文件扩展名
        self.extensions = {'.py', '.js', '.sh'}
    
    def calculate_file_hash(self, file_path: str) -> str:
        """计算文件哈希"""
        try:
            with open(file_path, 'rb') as f:
                return hashlib.md5(f.read()).hexdigest()
        except Exception as e:
            self.logger.error(f"Failed to calculate hash for {file_path}: {e}")
            return ""
    
    def detect_changes(self, force: bool = False) -> List[FileChange]:
        """检测文件变更"""
        changes = []
        
        if not self.input_dir.exists():
            self.logger.error(f"Input directory not found: {self.input_dir}")
            return changes
        
        # 查找所有文件
        current_files: Set[str] = set()
        for ext in self.extensions:
            current_files.update(str(f) for f in self.input_dir.rglob(f"*{ext}"))
        
        # 排除目录
        exclude_dirs = {'__pycache__', 'node_modules', '.git', 'venv', 'env'}
        current_files = {f for f in current_files if not any(excluded in f for excluded in exclude_dirs)}
        
        # 检测新增和修改
        for file_path in current_files:
            current_hash = self.calculate_file_hash(file_path)
            
            if file_path not in self.file_hashes:
                # 新增文件
                changes.append(FileChange(
                    file_path=file_path,
                    change_type='added',
                    new_hash=current_hash
                ))
            elif self.file_hashes[file_path] != current_hash:
                # 修改文件
                changes.append(FileChange(
                    file_path=file_path,
                    change_type='modified',
                    old_hash=self.file_hashes[file_path],
                    new_hash=current_hash
                ))
            
            # 更新哈希
            if current_hash:
                self.file_hashes[file_path] = current_hash
        
        # 检测删除
        deleted_files = set(self.file_hashes.keys()) - current_files
        for file_path in deleted_files:
            changes.append(FileChange(
                file_path=file_path,
                change_type='deleted',
                old_hash=self.file_hashes[file_path]
            ))
            del self.file_hashes[file_path]
        
        if changes and not force:
            self.logger.info(f"Detected {len(changes)} file changes")
        
        return changes
    
    def should_update_doc(self, changes: List[FileChange]) -> bool:
        """判断是否需要更新文档"""
        if not changes:
            return False
        
        # 只要有修改或新增，就需要更新
        for change in changes:
            if change.change_type in ('added', 'modified'):
                return True
        
        # 如果只是删除，检查是否还有其他文件
        if all(c.change_type == 'deleted' for c in changes):
            return True
        
        return False
    
    def setup_git_hooks(self, repo_path: str):
        """设置 Git Hooks"""
        try:
            repo = Path(repo_path)
            hooks_dir = repo / '.git' / 'hooks'
            
            if not hooks_dir.exists():
                self.logger.error(f"Git hooks directory not found: {hooks_dir}")
                return False
            
            # pre-commit hook
            pre_commit = hooks_dir / 'pre-commit'
            pre_commit_content = f"""#!/bin/bash
# Auto-generated by auto-document-generator

echo "Running auto-document-generator pre-commit hook..."

# 检查文档是否需要更新
if python -m auto_doc_generator check --input {self.input_dir}; then
    echo "Documentation is up to date"
else
    echo "Documentation needs updating"
    echo "Run: auto-doc-generator generate --input {self.input_dir} --output {self.output_dir}"
    exit 1
fi
"""
            
            pre_commit.write_text(pre_commit_content)
            pre_commit.chmod(0o755)
            
            # post-commit hook
            post_commit = hooks_dir / 'post-commit'
            post_commit_content = f"""#!/bin/bash
# Auto-generated by auto-document-generator

echo "Running auto-document-generator post-commit hook..."

# 自动生成文档
python -m auto_doc_generator generate --input {self.input_dir} --output {self.output_dir}

# 如果有变更，提交文档
if git diff --quiet {self.output_dir}; then
    echo "Documentation unchanged"
else
    echo "Committing updated documentation..."
    git add {self.output_dir}
    git commit -m "docs: auto-generate documentation"
fi
"""
            
            post_commit.write_text(post_commit_content)
            post_commit.chmod(0o755)
            
            self.logger.info(f"Git hooks installed in {hooks_dir}")
            return True
            
        except Exception as e:
            self.logger.error(f"Failed to setup git hooks: {e}")
            return False
    
    def start_watching(self, interval: int = 5):
        """开始监听目录（轮询模式）"""
        self.logger.info(f"Starting file watcher (interval: {interval}s)")
        self.logger.info(f"Watching: {self.input_dir}")
        self.logger.info(f"Output: {self.output_dir}")
        self.logger.info("Press Ctrl+C to stop")
        
        try:
            while True:
                # 检测变更
                changes = self.detect_changes()
                
                if self.should_update_doc(changes):
                    self.logger.info("Changes detected, regenerating documentation...")
                    
                    # 重新生成文档
                    self._regenerate_docs()
                    
                    self.logger.info("Documentation updated")
                
                # 等待
                time.sleep(interval)
                
        except KeyboardInterrupt:
            self.logger.info("Watch stopped by user")
        except Exception as e:
            self.logger.error(f"Watch failed: {e}")
    
    def start_watching_advanced(self):
        """开始监听目录（watchdog 模式）"""
        try:
            from watchdog.observers import Observer
            from watchdog.events import FileSystemEventHandler, FileModifiedEvent, FileCreatedEvent, FileDeletedEvent
            
            class DocGenHandler(FileSystemEventHandler):
                def __init__(self, watcher):
                    self.watcher = watcher
                    self.last_trigger = time.time()
                    self.debounce_interval = 1.0  # 1秒防抖
                
                def on_modified(self, event):
                    if not event.is_directory:
                        self._trigger_update(event.src_path)
                
                def on_created(self, event):
                    if not event.is_directory:
                        self._trigger_update(event.src_path)
                
                def on_deleted(self, event):
                    if not event.is_directory:
                        self._trigger_update(event.src_path)
                
                def _trigger_update(self, file_path: str):
                    # 检查文件扩展名
                    if not any(file_path.endswith(ext) for ext in self.watcher.extensions):
                        return
                    
                    # 防抖
                    current_time = time.time()
                    if current_time - self.last_trigger < self.debounce_interval:
                        return
                    
                    self.last_trigger = current_time
                    
                    self.watcher.logger.info(f"File changed: {file_path}")
                    
                    # 重新生成文档
                    self.watcher._regenerate_docs()
            
            # 创建观察者
            event_handler = DocGenHandler(self)
            observer = Observer()
            observer.schedule(event_handler, str(self.input_dir), recursive=True)
            
            # 开始观察
            observer.start()
            self.logger.info(f"Started watching with watchdog: {self.input_dir}")
            self.logger.info("Press Ctrl+C to stop")
            
            try:
                while observer.is_alive():
                    observer.join(1)
            except KeyboardInterrupt:
                observer.stop()
                self.logger.info("Watch stopped by user")
            
            observer.join()
            
        except ImportError:
            self.logger.warning("watchdog not available, falling back to polling mode")
            self.start_watching()
    
    def _regenerate_docs(self):
        """重新生成文档"""
        try:
            from .parser import CodeParser, detect_language
            from .extractor import CommentExtractor
            from .generator import DocumentGenerator
            
            # 解析代码
            parser = CodeParser(detect_language(str(self.input_dir)) or 'python')
            results = parser.parse_directory(str(self.input_dir))
            
            # 提取注释
            extractor = CommentExtractor()
            for result in results:
                for func in result.functions:
                    if func.docstring:
                        func.parsed_doc = extractor.parse_docstring(func.docstring)
            
            # 生成文档
            generator = DocumentGenerator()
            doc_content = generator.generate_api_doc(results)
            
            # 保存文档
            output_file = self.output_dir / 'API.md'
            generator.save_documentation(doc_content, str(output_file))
            
        except Exception as e:
            self.logger.error(f"Failed to regenerate docs: {e}")
    
    def setup_github_actions(self, repo_path: str):
        """设置 GitHub Actions 自动生成文档"""
        try:
            repo = Path(repo_path)
            workflows_dir = repo / '.github' / 'workflows'
            workflows_dir.mkdir(parents=True, exist_ok=True)
            
            # 创建 workflow 文件
            workflow = workflows_dir / 'docs.yml'
            workflow_content = f"""name: Generate Documentation

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.py'
      - '**.js'
      - '**.sh'
  pull_request:
    branches: [ main, master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install auto-doc-generator
    
    - name: Generate documentation
      run: |
        auto-doc-generator generate --input {self.input_dir} --output {self.output_dir}
    
    - name: Commit documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add {self.output_dir}
        git diff --quiet && git diff --staged --quiet || git commit -m "docs: auto-generate documentation"
        git push
"""
            
            workflow.write_text(workflow_content)
            
            self.logger.info(f"GitHub Actions workflow created: {workflow}")
            return True
            
        except Exception as e:
            self.logger.error(f"Failed to setup GitHub Actions: {e}")
            return False
