#!/usr/bin/env python3
"""
Regenerate serialization compatibility golden files for contract public types/events.

Usage:
  python3 contracts/scripts/gen_serialization_goldens.py
"""

from __future__ import annotations

import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


TUPLE_RE = re.compile(r'\("(?P<name>[^"]+)",\s+"(?P<hex>[0-9a-f]+)"\),')


def chunk(s: str, n: int = 80) -> list[str]:
    return [s[i : i + n] for i in range(0, len(s), n)]


def parse_expected_block(output: str) -> list[tuple[str, str]]:
    start_marker = "const EXPECTED: &[(&str, &str)] = &["
    start = output.find(start_marker)
    if start == -1:
        raise RuntimeError("Could not find EXPECTED block in test output.")
    end = output.find("];", start)
    if end == -1:
        raise RuntimeError("Could not find end of EXPECTED block in test output.")
    block = output[start : end + 2]
    items = TUPLE_RE.findall(block)
    if not items:
        raise RuntimeError("Parsed 0 golden entries from EXPECTED block.")
    return items


def write_goldens(dst: Path, items: list[tuple[str, str]]) -> None:
    lines: list[str] = []
    lines.append("// @generated by contracts/scripts/gen_serialization_goldens.py")
    lines.append("pub const EXPECTED: &[(&str, &str)] = &[")
    for name, hx in items:
        parts = chunk(hx, 80)
        if len(parts) == 1:
            rhs = f'"{parts[0]}"'
        else:
            rhs = "concat!(" + ", ".join(f'"{p}"' for p in parts) + ")"
        lines.append(f'    ("{name}", {rhs}),')
    lines.append("];")
    lines.append("")
    dst.write_text("\n".join(lines), encoding="utf-8")


@dataclass(frozen=True)
class Target:
    name: str
    workdir: Path
    cargo_cmd: list[str]
    goldens_path: Path


def run_target(target: Target) -> None:
    env = dict(os.environ)
    env["GRAINLIFY_PRINT_SERIALIZATION_GOLDENS"] = "1"

    proc = subprocess.run(
        target.cargo_cmd,
        cwd=target.workdir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"{target.name}: cargo test failed (exit {proc.returncode}).\n{proc.stdout}"
        )

    items = parse_expected_block(proc.stdout)
    write_goldens(target.goldens_path, items)
    print(f"{target.name}: wrote {target.goldens_path} ({len(items)} entries)")


def main() -> None:
    targets = [
        Target(
            name="bounty-escrow",
            workdir=ROOT / "contracts" / "bounty_escrow",
            cargo_cmd=[
                "cargo",
                "test",
                "-p",
                "bounty-escrow",
                "--lib",
                "serialization_compatibility_public_types_and_events",
                "--",
                "--nocapture",
            ],
            goldens_path=ROOT
            / "contracts"
            / "bounty_escrow"
            / "contracts"
            / "escrow"
            / "src"
            / "serialization_goldens.rs",
        ),
        Target(
            name="grainlify-core",
            workdir=ROOT / "contracts" / "grainlify-core",
            cargo_cmd=[
                "cargo",
                "test",
                "--lib",
                "serialization_compatibility_public_types_and_events",
                "--",
                "--nocapture",
            ],
            goldens_path=ROOT
            / "contracts"
            / "grainlify-core"
            / "src"
            / "serialization_goldens.rs",
        ),
        Target(
            name="program-escrow",
            workdir=ROOT / "contracts" / "program-escrow",
            cargo_cmd=[
                "cargo",
                "test",
                "--lib",
                "serialization_compatibility_public_types_and_events",
                "--",
                "--nocapture",
            ],
            goldens_path=ROOT
            / "contracts"
            / "program-escrow"
            / "src"
            / "serialization_goldens.rs",
        ),
    ]

    for t in targets:
        run_target(t)


if __name__ == "__main__":
    main()

