#!/bin/bash
# 查找抓包工具APK下载链接

echo "========================================"
echo "抓包工具APK下载链接汇总"
echo "========================================"

echo ""
echo "1️⃣ HttpCanary（推荐）"
echo "----------------------------------------"
echo "官方："
echo "  - Google Play: https://play.google.com/store/apps/details?id=com.guoshi.httpcanary"
echo "  - 官网: https://httpcanary.com/"
echo ""
echo "第三方："
echo "  - APKPure: https://apkpure.com/httpcanary/com.guoshi.httpcanary"
echo "  - APKMirror: https://www.apkmirror.com/apk/guoshi/httpcanary/"
echo ""

echo "2️⃣ Packet Capture"
echo "----------------------------------------"
echo "官方："
echo "  - Google Play: https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture"
echo ""
echo "第三方："
echo "  - APKPure: https://apkpure.com/packet-capture/app.greyshirts.sslcapture"
echo "  - APKMirror: https://www.apkmirror.com/apk/grey-shirts/packet-capture/"
echo ""

echo "3️⃣ HTTP Injector"
echo "----------------------------------------"
echo "官方："
echo "  - Google Play: https://play.google.com/store/apps/details?id=eu.chiroclinic.vpntunnel"
echo ""
echo "第三方："
echo "  - APKPure: https://apkpure.com/http-injector/eu.chiroclinic.vpntunnel"
echo ""

echo "4️⃣ NetCapture"
echo "----------------------------------------"
echo "官方："
echo "  - Google Play: https://play.google.com/store/apps/details?id=com.minhui.networkcapture.pro"
echo ""
echo "第三方："
echo "  - APKPure: https://apkpure.com/network-capture/com.minhui.networkcapture.pro"
echo ""

echo "========================================"
echo "推荐下载源（国内可访问）："
echo "========================================"
echo "1. APKPure（推荐）"
echo "   网址: https://apkpure.com"
echo "   特点: 无需Google Play，国内可访问"
echo ""
echo "2. 蓝奏云（备用）"
echo "   网址: https://www.lanzou.com"
echo "   特点: 国内下载速度快"
echo ""
echo "3. APKMirror（备用）"
echo "   网址: https://www.apkmirror.com"
echo "   特点: 安全可靠，版本全"
echo ""

echo "========================================"
echo "安装步骤："
echo "========================================"
echo "1. 下载APK文件"
echo "2. 手机设置 → 安全 → 允许未知来源"
echo "3. 点击APK安装"
echo "4. 打开应用，授予必要权限"
echo "5. 配置HTTPS证书"
echo "6. 开始抓包"
echo ""

echo "========================================"
echo "使用建议："
echo "========================================"
echo "✅ 优先使用HttpCanary（功能最全）"
echo "✅ 如果无法安装，尝试Packet Capture"
echo "✅ 如果都不行，使用电脑端Fiddler"
echo "========================================"
